baseURL: https://vladikk.com
disablePathToLower: true
languageCode: en-us
title: Rants on Software Design
theme: beautifulhugo
DefaultContentLanguage: en
pygmentsUseClasses: true
pygmentCodeFences: true
#disqusShortname: vladikk-blog
googleAnalytics: UA-40869819-1
publishDir: ../blog-public
unsafe: true
Params:
  subtitle: Vlad Khononov's personal blog
  logo: images/me-conf.jpg
  favicon: favicon.ico
  dateFormat: 'January 2, 2006'
  commit: false
  rss: true
  comments: true
Author:
  name: Vlad Khononov
  website: vladikk.com
  email: vladik@khononov.com
  facebook: vladikk
  github: vladikk
  twitter: vladikk
  linkedin: vladikkhononov
  stackoverflow: users/1736215/vladikk
  instagram: vladikkk
  telegram: vladik_kh
menu:
  main:
    - name: Consulting
      url: 'page/consulting'
      weight: 5
    - name: Blog
      url: ''
      weight: 2
    - name: Conferences
      url: page/speaking/
      weight: 3
    - name: Books
      url: 'page/books/'
      weight: 4
    - name: About & Contact
      url: page/about/
      weight: 6
